### ISSUE TITLE
Dockerizing FCN

### ISSUE THREAD

**Issue by dcunhas** [AgDSS/FCN.tensorflow#2]
## Requirements:
1. Must be able to create Docker container and trigger learning/prediction with one command from host machine (or other docker container).
2. Settings must be set in settings file (currently considering .ini file).
3. Docker container run command (i.e. mounts, etc.) must be triggered based on paths and settings in file
4. Training/prediction must be correctly triggered based on settings file, depositing output into specified mounted directory.
5. Docker container must stop once training/prediction is complete.

## Tasks
- [ ] Create sample .ini file with relevant and necessary values
- [ ] Create wrapper for FCN to run it based on settings in settings file
- [ ] Create wrapper for Docker run command to create instance based on settings
